language: node_js
before_install:
  - npm install -g npm
  - npm install -g grunt-cli
#  - npm install -g codeclimate-test-reporter
install:
  - npm install
script:
  - grunt travis-ci-build
after_success:
#  - CODECLIMATE_REPO_TOKEN=$codeclimate_repo_token codeclimate < lcov.info
  - grunt travis-ci-deploy
notifications:
  email:
    recipients:
      - touchthebeatdev@gmail.com
    on_success: change
    on_failure: always
