language: node_js
before_install: 
- npm install -g npm
- npm install -g grunt-cli
install: npm install
script: grunt travis-ci-build
after_success: grunt travis-ci-deploy
notifications:
  email:
    recipients:
      - touchthebeatdev@gmail.com
    on_success: change
    on_failure: always
